[workspace]
members = [
    "crates/canopee-cli",
    "crates/canopee-config",
    "crates/canopee-edge",
    "crates/canopee-e2e",
    "crates/canopee-gateway",
    "crates/canopee-identity",
    "crates/canopee-network",
    "crates/canopee-node",
    "crates/canopee-protocol",
    "crates/canopee-runtime",
    "crates/canopee-sdk",
    "crates/canopee-storage",
]
resolver = "3"