[package]
name = "canopee"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/canopee-cli", "crates/canopee-client", "crates/canopee-config","crates/canopee-identity", "crates/canopee-node", "crates/canopee-protocol", "crates/canopee-runtime", "crates/canopee-storage"]
resolver = "3"

[dependencies]
