[package]
name = "canopee-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1"
base64 = "0.22"
dirs = "5"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
futures = "0.3"
flate2 = "1"

canopee-identity = { path = "../canopee-identity" }
canopee-storage = { path = "../canopee-storage" }
canopee-sdk = { path = "../canopee-sdk" }
canopee-protocol = { path = "../canopee-protocol" }
canopee-runtime = { path = "../canopee-runtime" }
canopee-config = { path = "../canopee-config" }
canopee-gateway = { path = "../canopee-gateway" }
