[package]
name = "canopee-network"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bincode = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }

canopee-storage = { path = "../canopee-storage" }
canopee-identity = { path = "../canopee-identity" }
