[package]
name = "canopee-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bincode = "1"
tokio = { version = "1", features = ["full"] }

canopee-node = { path = "../canopee-node" }
canopee-protocol = { path = "../canopee-protocol" }
canopee-config = { path = "../canopee-config" }
